import os
import sys
import tempfile
import logging
from glob import glob

from ap_validator.app_package import AppPackage
import json

from .state import ApplicationState
from .ecr_helper import ECRHelper
from .ghcr_helper import GHCRHelper

from app_pack_generator import GitManager, DockerUtil, ApplicationNotebook
from app_pack_generator import ProcessCWL

logger = logging.getLogger(__name__)

class ApplicationGenerationError(Exception):
    pass

class UnityApplicationGenerator(object):

    def __init__(self, state_directory, source_repository=None, destination_directory=None, checkout=None,
                 repo2docker_config=None, use_namespace=None, use_repository=None, use_tag=None):

        if not ApplicationState.exists(state_directory):
            self.repo_info = self._localize_source(source_repository, destination_directory, checkout)
            self.app_state = ApplicationState(state_directory, self.repo_info.directory, source_repository)
        else:
            self.app_state = ApplicationState(state_directory)
            self.repo_info = self._localize_source(self.app_state.source_repository, self.app_state.app_base_path, checkout)

        # Use value from command line to override values saved into app state
        image_namespace = use_namespace if use_namespace is not None else self.app_state.docker_image_namespace
        image_repository = use_repository if use_repository is not None else self.app_state.docker_image_repository
        image_tag = use_tag if use_tag is not None else self.app_state.docker_image_tag

        self.docker_util = DockerUtil(self.repo_info, do_prune=False,
                                      repo_config=repo2docker_config,
                                      use_namespace=image_namespace,
                                      use_repository=image_repository,
                                      use_tag=image_tag)

        self.cwl_files_created = []

    def _localize_source(self, source, dest, checkout):

        # Check out original repository
        git_mgr = GitManager(source, dest)
    
        if checkout is not None:
            logger.info(f"Checking out {checkout} in {dest}")
            git_mgr.checkout(checkout)

        return git_mgr

    def create_docker_image(self):
 
        # These come either from the commandline or are generated by Docker util
        self.app_state.docker_image_namespace = self.docker_util.image_namespace
        self.app_state.docker_image_repository = self.docker_util.image_repository
        self.app_state.docker_image_tag = self.docker_util.image_tag

        # Create Docker image
        self.app_state.docker_image_reference = self.docker_util.build_image()

    def push_to_docker_registry(self, docker_registry):

        # Push to remote repository
        self.app_state.docker_url = self.docker_util.push_image(docker_registry, self.app_state.docker_image_reference)

    def push_to_aws_ecr(self):

        ecr_helper = ECRHelper(self.docker_util)

        # Create an ECR registry if it doesn't already exist
        ecr_helper.create_repository()

        # Log in to ECR via Docker
        registry_url = ecr_helper.docker_login()

        # Push docker image into ECR
        self.push_to_docker_registry(registry_url)

    def push_to_ghcr(self):

        ghcr_helper = GHCRHelper(self.docker_util)

        # Log in to GHCR via Docker
        registry_url = ghcr_helper.docker_login()

        # Push docker image into ECR
        self.push_to_docker_registry(registry_url)

    def create_cwl(self, cwl_output_path=None, docker_url=None, monolithic=False):

        # Fall through using docker_image_reference if docker_url does not exist because no push has occurred
        # Or if docker_url is supplied as an argument use that
        if docker_url is None and self.app_state.docker_url is not None:
            docker_url = self.app_state.docker_url
        elif docker_url is None and self.app_state.docker_image_reference is not None:
            docker_url = self.app_state.docker_image_reference
        elif docker_url is None:
            raise ApplicationGenerationError("Cannot create CWL files when Docker image tag or URL has not yet been registered through building and/or pushing Docker image")
        
        # Use passed CWL output path and set to app state, or else
        # use existing value from application state
        if cwl_output_path is not None:
            self.app_state.cwl_output_path = cwl_output_path
        else:
            cwl_output_path = self.app_state.cwl_output_path

        if not os.path.exists(cwl_output_path):
            os.makedirs(cwl_output_path)
    
        notebook_filename = os.path.join(self.repo_info.directory, "process.ipynb")

        app = ApplicationNotebook(notebook_filename)

        logger.info("Parameters:\n" + app.parameter_summary())
            
        # Create CWL files depending on the mode of production
        cwl_generators = [ ProcessCWL(app, self.repo_info) ]

        self.cwl_files_created = []
        for cwl_gen in cwl_generators:
            self.cwl_files_created += cwl_gen.generate_all(cwl_output_path, dockerurl=docker_url)
        
        return self.cwl_files_created

    def verify_cwl(self):

        for cwl_filename in self.cwl_files_created:
            logger.info(f"Verifying compliance of {cwl_filename} with OGC Best Practices")
            ap = AppPackage.from_url(cwl_filename)

            result = ap.check_all()

            issues = result["issues"]
            valid = result["valid"]

            for issue in issues:
                logger.error("{0}: {1}".format(issue["type"].upper(), issue["message"]))

            if valid:
                logger.info("CWL is compliant with the OGC's Best Practices for Earth Observation Application Packages")
            else:
                raise ApplicationGenerationError("CWL is NOT compliant with the OGC's Best Practices for Earth Observation Application Packages")

    def notebook_parameters(self):

        notebook_filename = os.path.join(self.repo_info.directory, "process.ipynb")

        nb = ApplicationNotebook(notebook_filename)

        params_str = "Parsed Notebook Parameters:\n"
        params_str += nb.parameter_summary()

        return params_str

    def notebook_metadata(self):

        notebook_filename = os.path.join(self.repo_info.directory, "process.ipynb")

        nb = ApplicationNotebook(notebook_filename)

        metadata_str = "Parsed Notebook Metadata:\n"
        metadata_str += nb.metadata_summary()

        return metadata_str